require "configs.impatient"
require "configs.nvim-cmp"

require "configs.lsp"
require "configs.telescope"
require "configs.treesitter"
require "configs.autopairs"
require "configs.comment"
require "configs.gitsigns"
require "configs.nvim-tree"
require "configs.bufferline"
require "configs.lualine"
require "configs.toggleterm"

require "configs.indentline"
require "configs.alpha"
