--##########################i#####################
--# Autocorrect/abbreviation-shortcut Dictionary #
--################################################
-- Just pressing space-bar after a misspelled word, will auto. change to the propper spelling|phrase.
-- Most ofthese were taken from a list of the top 100 most commonly misspelled English words.
vim.cmd
[[
  iab ture true
  iab flase false
  iab kevin. kevin.j.lausen@gmail.com
  iab i I
  iab teh the
  iab acomodate accommodate
  iab acommodate accommodate
  iab accomodate accommodate
  iab acheive achieve
  iab aquire acquire
  iab acros across
  iab adres address
  iab addres address
  iab adress address
  iab advertize advertise
  iab aparent apparent
  iab argumant argument
  iab athete athlete
  iab aweful awful
  iab balkanse balance
  iab bandwith bandwidth
  iab basicly basically
  iab basicaly basically
  iab becomming becoming
  iab begining beginning
  iab beleive believe
  iab bennefit benefit
  iab briliant brilliant
  iab busines business
  iab calender calendar
  iab carefull careful
  iab catagory category
  iab cieling ceiling
  iab comming coming
  iab citicen citizen
  iab conveneince convenience
  iab competittion competition
  iab critisize criticize
  iab develope develop
  iab desprate desperate
  iab diference difference
  iab dilema dilemma
  iab disapear disappear
  iab dissapear disappear
  iab distrobution distribution
  iab disapoint disappoint
  iab dissapoint disappoint
  iab disipline discipline
  iab dos does
  iab duering during
  iab iether  either
  iab embaras embarrass
  iab embarass embarrass
  iab embarras embarrass
  iab envirenment environment
  iab equiped equipped
  iab exagerate exaggerate
  iab excelent excellent
  iab exept except
  iab experiense experience
  iab facsinating fascinating
  iab finaly finally
  iab foriegn foreign
  iab fourty forty
  iab fundimental fundamental
  iab generaly generally
  iab govermint government
  iab goverment government
  iab gramar grammar
  iab garantee guarentee
  iab giedence  guidence
  iab hapiness happiness
  iab horedously horrendously
  iab hero heroe
  iab humerous humorous
  iab imatation imitation
  iab immitation imitation
  iab imediately immediately
  iab incidentaly incidentally
  iab indipendent independent
  iab independiny independent
  iab intristing interesting
  iab interfer interfere
  iab interpratation interpretation
  iab interuption interruption
  iab irelevant irrelevant
  iab irrelivant irrelevant
  iab irrelevint irrelevant
  iab iland island
  iab jelous jealous
  iab jealus jealous
  iab judgement judgment
  iab laboritory laboratory
  iab lenth length
  iab leson lesson
  iab lisense license
  iab lonlines lonliness
  iab loseing losing
  iab lieing lying
  iab mariage marriage
  iab marage marriage
  iab mathimatics mathematics
  iab mathamatics mathematics
  iab medisine medicine
  iab miniture miniature
  iab minite minute
  iab mystyrious mysterious
  iab naturaly naturally
  iab necesary necessary
  iab nieghbor neighbor
  iab niether neither
  iab noticable noticeable
  iab ocasion occasion
  iab ocasional occasional
  iab ocured occurred
  iab occured occurred
  iab ocurred occurred
  iab oficial official
  iab oftan often
  iab oftin often
  iab omision omission
  iab oparate operate
  iab opirate operate
  iab optamism optimism
  iab paralel parallel
  iab particalary particulary
  iab percieve perceive
  iab perminant permanent
  iab permanint permanent
  iab perservere persevere
  iab persavere persevere
  iab persade persuade
  iab personel personnel
  iab peice piece
  iab planing planning
  iab plesant pleasant
  iab politicul political
  iab politacala political
  iab poses possess
  iab posses possess
  iab posess possess
  iab posible possible
  iab practacle practicle
  iab prafer prefer
  iab prifer prefer
  iab predjudice prejudice
  iab presince presence
  iab privalege privilege
  iab privledge privilage
  iab privlege privilege
  iab probly probably
  iab profesional professional
  iab promis promise
  iab psycology psychology
  iab quantaty quantity
  iab quartar quarter
  iab realise realize
  iab recieve receive
  iab recognise recognize
  iab recomend recommend
  iab recamend recommend
  iab recammend recommend
  iab refrence reference
  iab religus religious
  iab religius religious
  iab repatition repitition
  iab resturant restaurant
  iab rhythem rhythm
  iab rhythum rhythm
  iab rediculous ridiculous
  iab sacrafice sacrifice
  iab safty safety
  iab scisors scissors
  iab secratary secretary
  iab shinning shining
  iab simaler similar
  iab soldeir soldier
  iab speach speech
  iab stoping stopping
  iab suceed succeed
  iab sucessful successful
  iab sucesful successful
  iab succesful successful
  iab surly surely
  iab tempurature temperature
  iab temperary temporary
  iab thruogh through
  iab towrd toward
  iab treis tries
  iab truley truly
  iab twelvth twelfth
  iab usualy usually
  iab vilage village
  iab wierd weird
  iab welcom welcome
]]
